// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrtrahqjxiygjbjsckwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpydHJhaHFqeGl5Z2pianNja3duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwNjA1MTQsImV4cCI6MjA1MTYzNjUxNH0.UuAJz9c74tZRthb3yrwbJUrXv4T_2cacpje4SCgXYFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);